language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install .
  - pip install -r requirements.txt
script: py.test tests
notifications:
  slack:
    secure: a7b+T/TFWf5mObxdH/jhxoz91e5cxJyYFNNX9A9i4NRLANYBodOS/rqoUegehs0jX0QXPqdsfJGGtQfiwcFW6gGGfkZ9T1muJlGAHyWkSBKUe3DE2j4eiTdzU4a1nvZleUl4XPlLZLUYWi4oAkcp7cjgxWXXh7+1NBqjSrapuPQ=
deploy:
  provider: pypi
  user: elliottsj
  password:
    secure: Ec8Xr72T/coj0t1EjKO5mX/6fyHKqj3WNVQ/SOx9mRIEyUeeWU0wwJxaL4IxpSkFIF2zWl4N0LwRLWW4QcXweSs/YSmM3H6uz0ppWprqgQSrxPuymRuBA/zGMrUyMPwM/GtsMXAE76OAzajiJvGjIpql57h1ZpTwbQcpo636pSk=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: sherlocke/pywatson
