language: python
python:
  - '2.7'
  - '3.4'
script: py.test
notifications:
  slack:
    secure: ABYHsNZGOJRpgDPAKGm3geztFMPgn3vw+n44lKk1H3MkbKrC2GpY71zEr2haFbT9azFsUPH7H+zaaS0GaZCSOFiafD9WMscroh5tbG4vUJIcNrRImv3bCgGDBnms/xzdBmty0avy6v7LL6PZkG3MBrbT/ZjB+JznGGdqExrETJE=
